[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1
via_ir = true

[profile.default.optimizer_details]
yul = true
constantOptimizer = true
deduplicate = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = "dhfoDgvulfnTUtnIf[xa[r]EscLMcCTUtTOntnfDIulLculVcul[j]Tpeulxa[rul]xa[r]cLgvifCTUca[r]LSsTOtfDnca[r]Iulc]jmul[jul]VcTOculjmul"
evm_version = "cancun"
